server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_bootcamp_onclass?createDatabaseIfNotExist=true
    username: root
    password: Miguel2015
  jpa:
    hibernate:
      ddl-auto: update